version: "3"
services:
  # cats-api:
  #   container_name: monorepo-cats-api
  #   build:
  #     context: .
  #     dockerfile: ./apps/cats-api/Dockerfile
  #   ports:
  #     - "3000:3000"
  #     - "5870:5870"
  #   volumes:
  #     - .:/src:cached
  user-api:
    container_name: monorepo-user-api
    build:
      context: .
      dockerfile: ./apps/user-api/Dockerfile
    ports:
      - "4000:4000"
      - "5880:5880"
    volumes:
      - .:/src:cached
