version: '3'

services:
  db-postgresql:
    image: postgis/postgis:14-3.3-alpine
    container_name: monorepo-postgres.postgis
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    restart: always
  db-mongo:
    container_name: monorepo-mongo
    image: mongo
    env_file:
      - docker.env
    ports:
      - 27017:27017
  mongo-express:
    container_name: monorepo-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - db-mongo
    ports:
      - 8082:8082
    env_file:
      - docker.env
  redis:
    container_name: monorepo-redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
  redis-commander:
    container_name: monorepo-redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    env_file:
      - docker.env
    ports:
      - '8081:8081'
  # elasticsearch:
  #   container_name: monorepo_elasticsearch
  #   image: elasticsearch:7.11.2
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   environment:
  #     - node.name=elasticsearch
  #     - cluster.name=es-docker-cluster
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  # kibana:
  #   container_name: monorepo-kibana
  #   image: kibana:7.11.2
  #   ports:
  #     - '5601:5601'
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  # jaegertracing:
  #   container_name: monorepo_jaegertracing
  #   image: jaegertracing/all-in-one:latest
  #   env_file:
  #     - docker.env
  #   ports:
  #     - '5775:5775/udp'
  #     - '6831:6831/udp'
  #     - '6832:6832/udp'
  #     - '5778:5778'
  #     - '16686:16686'
  #     - '14268:14268'
  #     - '9411:9411'
